################################################################################
### generated-with:
###   type: R-package
###   name: kwb.pkgbuild
###   version: 0.2.3
###   installed-from: https://kwb-r.r-universe.dev (R 4.4.1)
###   installed-on: '2024-10-15'
### generated-by:
###   user: mrustl
###   function-call: kwb.pkgbuild::create_empty_branch_ghpages(pkg$name)
### generated-on: 2024-10-31 14:14:15.625046
################################################################################


pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r * .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - gh-pages
